In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.preprocessing import PowerTransformer
import h5py

warnings.filterwarnings('ignore')
# 设置中文显示
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [2]:
"""
_ratio.mat是比值，_DE.mat是动态熵
ratio是7session*16subject*3channel(FzCzPz)，DE是7session*16subject*3channel*2band(low, high)
"""

'\n_ratio.mat是比值，_DE.mat是动态熵\nratio是7session*16subject*3channel(FzCzPz)，DE是7session*16subject*3channel*2band(low, high)\n'

In [13]:
# 使用原始字符串避免路径转义问题
# file_path = r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\熵\A_DE_landing_betaband.mat"
file_path = r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_alpVShi_ratio.mat"

# 打开 .mat 文件
with h5py.File(file_path, "r") as f:
    print("🔹 文件中所有顶层变量：")
    print(list(f.keys()))

    print("\n🔹 文件层级结构：")


    def print_tree(name, obj):
        print(name)


    f.visititems(print_tree)

    # 示例：如果文件中有变量 "data"，这样读取：
    # data = f["data"][:]
    # print("\n读取的 data：", data)

🔹 文件中所有顶层变量：
['A_alpVShi_ratio']

🔹 文件层级结构：
A_alpVShi_ratio

In [32]:
"""
文件列表：
A_alpVShi_ratio.mat
A_alpVSlow_ratio.mat
A_theVShi_ratio.mat
A_theVSlow_ratio

B_alpVShi_ratio.mat
B_alpVSlow_ratio.mat
B_theVShi_ratio.mat
B_theVSlow_ratio.mat

文件名含义：
其中A代表alcohol组，B代表control组，ratio代表频段的比值，alp代表alpha频段，the代表theta频段，VS代表做比值运算，low代表beta_low频段，hi代表beta_high频段，

文件内容：
每个文件内容的形状：3channel(FzCzPz)*16subject*7session

names_A = ["曾奇", "王榕榕", "徐梓军", "徐文婷", "达格吉", "李天琦", "王威", "张渊博", "黄博文",
           "朱祖恩", "刘子皓", "李嘉文", "徐子焰", "李国荣", "杨珊珊", "付瑞晗"]

names_B = ["杜佳鑫", "冯科嘉", "陈妍", "胡浩男", "王子铭", "程腾宇", "朱娇娇", "祖丽米热", "毛华灏", "郭浚杰", "周鑫颜",
           "肖雨晨", "冯晓娅", "刘勇杰", "祝鹏程", "董嘉乐"]
"""

'\n文件列表：\nA_alpVShi_ratio.mat\nA_alpVSlow_ratio.mat\nA_theVShi_ratio.mat\nA_theVSlow_ratio\n\nB_alpVShi_ratio.mat\nB_alpVSlow_ratio.mat\nB_theVShi_ratio.mat\nB_theVSlow_ratio.mat\n\n文件名含义：\n其中A代表alcohol组，B代表control组，ratio代表频段的比值，alp代表alpha频段，the代表theta频段，low代表beta_low频段，high代表beta_high频段，VS代表做比值运算\n\n文件内容：\n每个文件内容的形状：3channel(FzCzPz)*16subject*7session\n'

In [1]:
# 所有文件路径整理成字典
file_paths = {
    "A_alpVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_alpVShi_ratio.mat",
    "A_alpVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_alpVSlow_ratio.mat",
    "A_theVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_theVShi_ratio.mat",
    "A_theVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_theVSlow_ratio.mat",

    "B_alpVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_alpVShi_ratio.mat",
    "B_alpVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_alpVSlow_ratio.mat",
    "B_theVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_theVShi_ratio.mat",
    "B_theVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_theVSlow_ratio.mat",
}
# _ratio.mat是比值
# 自动循环读取
for key, path in file_paths.items():
    with h5py.File(path, "r") as f:
        # 形状：3channel(FzCzPz)*16subject*7session
        dset = f[key]  # dataset 名与 key 一致
        print(f"{key} 形状： {dset.shape}")

NameError: name 'h5py' is not defined

In [59]:
# 你的文件路径字典
file_paths = {
    "A_alpVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_alpVShi_ratio.mat",
    "A_alpVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_alpVSlow_ratio.mat",
    "A_theVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_theVShi_ratio.mat",

    "A_theVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\A_theVSlow_ratio.mat",
    "B_alpVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_alpVShi_ratio.mat",
    "B_alpVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_alpVSlow_ratio.mat",
    "B_theVShi_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_theVShi_ratio.mat",
    "B_theVSlow_ratio": r"E:\pycharm all files\眼动数据处理\相关性分析\数据\原始数据\eeg比值&熵\比值\B_theVSlow_ratio.mat",
}

# 3 channels 的标签
channels = ["Fz", "Cz", "Pz"]

# 最终保存所有行
rows = []

for key, path in file_paths.items():
    with h5py.File(path, "r") as f:
        data = f[key][()]  # shape = (3,16,7)

    # key 信息解析，例如：A_alpVShi_ratio
    group = key[0]  # A / B
    ratio_type = key[2:-6]  # 去掉 "A_" 和 "_ratio"

    # 展开数据
    for ch_idx in range(3):
        for subj in range(16):
            for sess in range(7):
                value = data[ch_idx, subj, sess]

                # ⭐ 合并新指标 metric
                metric = f"{channels[ch_idx]}_{ratio_type}"
                rows.append({
                    "group": group,
                    "metric": metric,
                    "subject": subj + 1,
                    "session": sess + 1,
                    "value": float(value)
                })

# 转为 DataFrame
df = pd.DataFrame(rows)

df

     group       metric  subject  session     value
0        A   Fz_alpVShi        1        1 -0.726087
1        A   Fz_alpVShi        1        2  0.934976
2        A   Fz_alpVShi        1        3  0.649456
3        A   Fz_alpVShi        1        4  0.241250
4        A   Fz_alpVShi        1        5  0.352503
...    ...          ...      ...      ...       ...
2683     B  Pz_theVSlow       16        3  2.798627
2684     B  Pz_theVSlow       16        4  3.072946
2685     B  Pz_theVSlow       16        5  0.620206
2686     B  Pz_theVSlow       16        6  1.657167
2687     B  Pz_theVSlow       16        7  0.823056

[2688 rows x 5 columns]

In [60]:
# A组与B组姓名
names_A = ["曾奇", "王榕榕", "徐梓军", "徐文婷", "达格吉", "李天琦", "王威", "张渊博",
           "黄博文", "朱祖恩", "刘子皓", "李嘉文", "徐子焰", "李国荣", "杨珊珊", "付瑞晗"]

names_B = ["杜佳鑫", "冯科嘉", "陈妍", "胡浩男", "王子铭", "程腾宇", "朱娇娇", "祖丽米热",
           "毛华灏", "郭浚杰", "周鑫颜", "肖雨晨", "冯晓娅", "刘勇杰", "祝鹏程", "董嘉乐"]

# 构建映射字典
map_A = {i + 1: names_A[i] for i in range(len(names_A))}  # 1–16
map_B = {i + 1: names_B[i] for i in range(len(names_B))}  # 1–16

# 根据 group 替换 subject → name
df["name"] = df.apply(lambda row:
                      map_A[row["subject"]] if row["group"] == "A"
                      else map_B[row["subject"]],
                      axis=1)

# 如不需要原 subject 列，可删除
df = df.drop(columns=["subject"])

In [61]:
# pivot wider: metric 作为新列
df_wide = df.pivot_table(
    index=["name", "group", "session"],
    columns="metric",
    values="value"
).reset_index()

# 可选：列名扁平化（防止 MultiIndex）
df_wide.columns.name = None

df_wide

,name,group,session,Cz_alpVShi,Cz_alpVSlow,Cz_theVShi,Cz_theVSlow,Fz_alpVShi,Fz_alpVSlow,Fz_theVShi,Fz_theVSlow,Pz_alpVShi,Pz_alpVSlow,Pz_theVShi,Pz_theVSlow
0,付瑞晗,A,1,-1.437180,-1.532164,-1.287953,-1.373074,-4.117628,-2.761845,-4.050715,-2.716964,1.460518,1.572004,1.308313,1.408181
1,付瑞晗,A,2,2.105166,2.106585,1.666796,1.667920,1.186010,1.392895,0.911831,1.070889,2.053216,5.278246,1.767573,4.543939
2,付瑞晗,A,3,-4.690412,1.328775,-4.649697,1.317241,1.020330,1.174340,0.878509,1.011112,1.058269,0.795306,0.601766,0.452237
3,付瑞晗,A,4,0.289411,0.593283,0.056982,0.116811,0.402521,1.264330,0.286452,0.899754,-5.516007,0.603882,-8.017515,0.877743
4,付瑞晗,A,5,0.808523,0.828338,0.707111,0.724440,0.654791,0.786245,0.467395,0.561229,0.654377,1.452079,0.224516,0.498206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,黄博文,A,3,-26.836166,3.018931,-17.350251,1.951814,0.391636,0.380273,-0.337249,-0.327464,0.802374,0.494465,0.268580,0.165513
220,黄博文,A,4,0.123521,-1.329368,-0.218965,2.356575,0.573553,4.306484,0.270505,2.031069,-0.891352,0.664819,-2.312444,1.724746
221,黄博文,A,5,-0.236181,-0.199533,-0.083509,-0.070551,-1.037006,-0.907792,-2.130666,-1.865179,0.415680,2.817726,-0.224159,-1.519484
222,黄博文,A,6,1.164713,11.347848,1.755522,17.104127,1.572951,1.869395,1.525896,1.813472,1.465835,2.068649,1.406136,1.984400
223,黄博文,A,7,0.897347,0.813703,0.823621,0.746849,1.236590,0.888744,0.709979,0.510266,0.408638,0.359192,-0.158374,-0.139211

In [62]:
df_wide.group = df_wide.group.replace({"A": "Alcohol", "B": "Control"})
df_wide.columns = ['受试者', '组别', 'session', 'Cz_alpVShi', 'Cz_alpVSlow', 'Cz_theVShi',
                   'Cz_theVSlow', 'Fz_alpVShi', 'Fz_alpVSlow', 'Fz_theVShi', 'Fz_theVSlow',
                   'Pz_alpVShi', 'Pz_alpVSlow', 'Pz_theVShi', 'Pz_theVSlow']
df_wide

,受试者,组别,session,Cz_alpVShi,Cz_alpVSlow,Cz_theVShi,Cz_theVSlow,Fz_alpVShi,Fz_alpVSlow,Fz_theVShi,Fz_theVSlow,Pz_alpVShi,Pz_alpVSlow,Pz_theVShi,Pz_theVSlow
0,付瑞晗,Alcohol,1,-1.437180,-1.532164,-1.287953,-1.373074,-4.117628,-2.761845,-4.050715,-2.716964,1.460518,1.572004,1.308313,1.408181
1,付瑞晗,Alcohol,2,2.105166,2.106585,1.666796,1.667920,1.186010,1.392895,0.911831,1.070889,2.053216,5.278246,1.767573,4.543939
2,付瑞晗,Alcohol,3,-4.690412,1.328775,-4.649697,1.317241,1.020330,1.174340,0.878509,1.011112,1.058269,0.795306,0.601766,0.452237
3,付瑞晗,Alcohol,4,0.289411,0.593283,0.056982,0.116811,0.402521,1.264330,0.286452,0.899754,-5.516007,0.603882,-8.017515,0.877743
4,付瑞晗,Alcohol,5,0.808523,0.828338,0.707111,0.724440,0.654791,0.786245,0.467395,0.561229,0.654377,1.452079,0.224516,0.498206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,黄博文,Alcohol,3,-26.836166,3.018931,-17.350251,1.951814,0.391636,0.380273,-0.337249,-0.327464,0.802374,0.494465,0.268580,0.165513
220,黄博文,Alcohol,4,0.123521,-1.329368,-0.218965,2.356575,0.573553,4.306484,0.270505,2.031069,-0.891352,0.664819,-2.312444,1.724746
221,黄博文,Alcohol,5,-0.236181,-0.199533,-0.083509,-0.070551,-1.037006,-0.907792,-2.130666,-1.865179,0.415680,2.817726,-0.224159,-1.519484
222,黄博文,Alcohol,6,1.164713,11.347848,1.755522,17.104127,1.572951,1.869395,1.525896,1.813472,1.465835,2.068649,1.406136,1.984400
223,黄博文,Alcohol,7,0.897347,0.813703,0.823621,0.746849,1.236590,0.888744,0.709979,0.510266,0.408638,0.359192,-0.158374,-0.139211

In [63]:
df_else = pd.read_excel(
    r"E:\pycharm all files\眼动数据处理\相关性分析\数据\预处理后的数据\按session分开的_eeg&eye&scl&ppg.xlsx")
df_else.columns

Index(['组别', '受试者', 'session', 'SCL_mean_yj', 'AOI转换次数', '静态注释熵(SGE)',
       '眼跳注视熵(GTE)', 'HR', 'SDNN', 'RMSSD', 'AMP', 'EEG_beta_high_Cz_mean',
       'EEG_beta_high_Fz_mean', 'EEG_beta_high_Pz_mean',
       'EEG_beta_low_Cz_mean', 'EEG_beta_low_Fz_mean', 'EEG_beta_low_Pz_mean'],
      dtype='object')

In [64]:
df_merged = pd.merge(
    df_else,
    df_wide,
    on=["组别", "受试者", "session"],
    how="inner"
)
df_merged

,组别,受试者,session,SCL_mean_yj,AOI转换次数,静态注释熵(SGE),眼跳注视熵(GTE),HR,SDNN,RMSSD,...,Cz_theVShi,Cz_theVSlow,Fz_alpVShi,Fz_alpVSlow,Fz_theVShi,Fz_theVSlow,Pz_alpVShi,Pz_alpVSlow,Pz_theVShi,Pz_theVSlow
0,Alcohol,付瑞晗,1,0.008423,5.964286,0.793663,0.297438,17.819101,-3.260506,1.857342,...,-1.287953,-1.373074,-4.117628,-2.761845,-4.050715,-2.716964,1.460518,1.572004,1.308313,1.408181
1,Alcohol,付瑞晗,2,0.008640,10.500000,0.884336,0.313038,5.119280,-15.197881,-21.082419,...,1.666796,1.667920,1.186010,1.392895,0.911831,1.070889,2.053216,5.278246,1.767573,4.543939
2,Alcohol,付瑞晗,3,0.008858,15.035714,0.975010,0.328639,9.814463,11.623381,13.436624,...,-4.649697,1.317241,1.020330,1.174340,0.878509,1.011112,1.058269,0.795306,0.601766,0.452237
3,Alcohol,付瑞晗,4,0.009075,19.571429,1.065683,0.344240,44.991362,25.830811,31.173141,...,0.056982,0.116811,0.402521,1.264330,0.286452,0.899754,-5.516007,0.603882,-8.017515,0.877743
4,Alcohol,付瑞晗,5,0.009293,24.107143,1.156356,0.359840,10.378346,33.789581,41.231056,...,0.707111,0.724440,0.654791,0.786245,0.467395,0.561229,0.654377,1.452079,0.224516,0.498206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,Control,陈妍,3,-0.070973,21.535714,1.521286,0.548103,-2.053871,38.025352,38.134196,...,4.543758,-1.649062,5.067337,59.993978,4.614078,54.627684,10.506800,8.394237,10.802331,8.630346
220,Control,陈妍,4,-0.088214,18.071429,1.326411,0.441623,-6.284982,-16.635726,-24.647037,...,2.634036,2.996113,-28.040737,21.678034,-23.036226,17.809093,-0.459137,1.321222,0.309093,-0.889454
221,Control,陈妍,5,-0.105455,14.607143,1.131536,0.335144,-1.159217,17.134339,17.823007,...,1.589667,-1.248641,-0.514815,-0.534875,0.899574,0.934625,-0.275669,-0.242793,1.219859,1.074378
222,Control,陈妍,6,-0.122697,11.142857,0.936661,0.228664,-5.534589,-22.075732,-34.098901,...,2.631512,6.660803,-3.974958,-1.820669,-3.265536,-1.495729,-1.902672,1.656347,1.280889,-1.115062
223,Control,陈妍,7,-0.139938,7.678571,0.741786,0.122184,6.630030,42.814378,48.559906,...,-0.961307,-0.284800,-0.562594,-0.232235,0.983061,0.405801,-0.158644,-0.108820,0.702015,0.481536

In [66]:
df_merged.to_excel(
    "E:\pycharm all files\眼动数据处理\相关性分析\数据\预处理后的数据\按session分开的_eeg&eye&scl&ppg+eeg_ratio.xlsx",
    index=False)